### ISSUE TITLE
I am stupid, how do i use ros2 with docker on m1?

### ISSUE THREAD

**Issue by ErnestWang31** [adeeb10abbas/ros2-docker-dev#4]
I know its not directly related to this repo, but some help would be appreciated :)

**Comment by adeeb10abbas** [comment]
What exactly is the issue that you're running into?

**Comment by totosan** [comment]
Not sure, if this is the answer to the question, nor if @ErnestWang31 's issue is related, but I also cannot use this with M1.
I found that the NoVNC image used in the docker-compose is just for the amd64 arch.
I quickly cloned the novnc repo and built it on my Mac locally. Afterwards, it ran like a charm.
Asking myself, why you @adeeb10abbas started this project with M1 and didn't have this issue. :-)

**Comment by adeeb10abbas** [comment]
Interesting - in the `docker-compose.yml` it's only pulling the[ `theasp/novnc:latest` ](https://github.com/adeeb10abbas/ros2-docker-dev/blob/e314e2860105ca32993f600cc6042f9afacf9a15/docker-compose.yml#L25)

Could you please share the error that you get without building locally? I *just* did a fresh re-run and I only see a warning that the image is for `amd64` but that should still be able to run the image in emulation. Here's my screenshot of it running - 
<img width="1431" alt="image" src="https://github.com/adeeb10abbas/ros2-docker-dev/assets/38449494/d6a7ffda-0112-44f5-88dd-334a1596c48c">
